name: flutter_asset_generator
email: cjl_spy@163.com
homepage: https://github.com/CaiJingLong/flutter_resource_generator
version: 0.6.1
description: Automatically generate a resource file by scanning pubspec.yaml to correspond to the flutter's asset, imitation R file short name.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  args: ^2.0.0
  dart_style: ^1.3.8
  glob: ^2.0.0
  io: ^0.3.3
  path: ^1.6.4
  yaml: ^3.1.0

executables:
  fgen: resource_generator
