name: flutter_asset_generator
author: caijinglong<cjl_spy@163.com>
email: cjl_spy@163.com
homepage: https://github.com/CaiJingLong/flutter_resource_generator
version: 0.1.2
description: with flutter auto generate a dart file.

environment:
  sdk: '>=2.0.0-dev.51.0 <3.0.0'

dependencies:
  build: ^0.12.7+3
  build_config: ^0.3.1+2
  yaml: ^2.1.14

dev_dependencies:
  build_runner: ^0.10.0