name: flutter_asset_generator
author: caijinglong<cjl_spy@163.com>
email: cjl_spy@163.com
homepage: https://github.com/CaiJingLong/flutter_resource_generator
version: 0.3.0+1
description: with flutter auto generate a dart file.

environment:
  sdk: '>=2.0.0-dev.51.0 <3.0.0'

dependencies:
  yaml: ^2.1.15
  path: ^1.6.2
  args: ^1.5.1

executables:
  fgen: resource_generator
